### ISSUE TITLE
I am getting Exception on  - view.java

### ISSUE THREAD

**Issue by pritammalunjkar** [vrjgamer/Custom-Alert-Dialog-Box#1]
2020-03-30 08:56:30.612 10626-10626/mosquit.aai.com.i_mosquit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mosquit.aai.com.i_mosquit, PID: 10626
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4725)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4720)
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class TextView
     Caused by: android.content.res.Resources$NotFoundException: Drawable mosquit.aai.com.i_mosquit:color/abc_background_cache_hint_selector_material_light with resource ID #0x7f050001
     Caused by: android.content.res.Resources$NotFoundException: File res/color-v11/abc_background_cache_hint_selector_material_light.xml from drawable resource ID #0x7f050001
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
        at android.content.res.Resources.loadDrawable(Resources.java:858)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.view.View.<init>(View.java:4202)
        at android.widget.TextView.<init>(TextView.java:710)
        at android.widget.TextView.<init>(TextView.java:704)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:40)
        at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:806)
        at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:836)
        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at mosquit.aai.com.i_mosquit.activities.screeningActivity.customAlertDaliog(screeningActivity.java:482)
        at mosquit.aai.com.i_mosquit.activities.screeningActivity.CalculateRisk(screeningActivity.java:474)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4720)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable
2020-03-30 08:56:30.615 10626-10626/mosquit.aai.com.i_mosquit E/AndroidRuntime:     at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:183)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
        at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
        	... 32 more2020-03-30 08:56:30.612 10626-10626/mosquit.aai.com.i_mosquit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mosquit.aai.com.i_mosquit, PID: 10626
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4725)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4720)
        at android.view.View.performClick(View.java:5637) 
        at android.view.View$PerformClick.run(View.java:22429) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
     Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class TextView
     Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class TextView
     Caused by: android.content.res.Resources$NotFoundException: Drawable mosquit.aai.com.i_mosquit:color/abc_background_cache_hint_selector_material_light with resource ID #0x7f050001
     Caused by: android.content.res.Resources$NotFoundException: File res/color-v11/abc_background_cache_hint_selector_material_light.xml from drawable resource ID #0x7f050001
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:725)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:571)
        at android.content.res.Resources.loadDrawable(Resources.java:858)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:928)
        at android.view.View.<init>(View.java:4202)
        at android.widget.TextView.<init>(TextView.java:710)
        at android.widget.TextView.<init>(TextView.java:704)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:44)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:40)
        at android.support.v7.internal.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
        at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:806)
        at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:836)
        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at mosquit.aai.com.i_mosquit.activities.screeningActivity.customAlertDaliog(screeningActivity.java:482)
        at mosquit.aai.com.i_mosquit.activities.screeningActivity.CalculateRisk(screeningActivity.java:474)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:4720)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable
2020-03-30 08:56:30.615 10626-10626/mosquit.aai.com.i_mosquit E/AndroidRuntime:     at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:183)
        at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:116)
        at android.graphics.drawable.DrawableInflater.inflateFromXml(DrawableInflater.java:130)
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1227)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1200)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:715)
        	... 32 more[](url)

**Comment by vrjgamer** [comment]
Can you provide the code snippet of your xml layout and the java code?
it seems like you are trying to access some resource that does not exist. And please do not use onClick attribute via xml layout. As this is a dynamic inflation it may cause problem, instead attach the button a onClickListener after the layout is inflated.
